general:
  use_uvloop: true
  logging:
    console:
      _type: console
      level: WARN

llms:
  nim_llm:
    _type: nim
    model_name: meta/llama-3.1-70b-instruct
    temperature: 0.0

functions:
  # Define the main agent function
  blakes_bot:
    _type: blakes_bot
    llm_name: nim_llm
    max_history: 10
    description: "A math assistant that can subtract numbers and remember results"
    verbose: true

workflow:
  _type: blakes_bot
  llm_name: nim_llm
  verbose: true
  max_history: 10
  description: "A math assistant that can subtract numbers and remember results"
